services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - $PWD/seed:/seed
      - $PWD/seed/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=admin
