wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/install.sql

pushd data
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/AWBuildVersion.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/Address.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/AddressType.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/BillOfMaterials.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/BusinessEntity.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/BusinessEntityAddress.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/BusinessEntityContact.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/ContactType.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/CountryRegion.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/CountryRegionCurrency.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/CreditCard.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/Culture.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/Currency.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/CurrencyRate.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/Customer.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/Department.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/Document.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/EmailAddress.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/Employee.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/EmployeeDepartmentHistory.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/EmployeePayHistory.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/ErrorLog.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/Illustration.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/JobCandidate.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/JobCandidate_TOREMOVE.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/Location.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/Password.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/Person.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/PersonCreditCard.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/PersonPhone.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/PhoneNumberType.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/Product.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/ProductCategory.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/ProductCostHistory.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/ProductDescription.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/ProductDocument.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/ProductInventory.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/ProductListPriceHistory.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/ProductModel.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/ProductModelIllustration.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/ProductModelProductDescriptionCulture.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/ProductModelorg.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/ProductPhoto.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/ProductProductPhoto.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/ProductReview.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/ProductSubcategory.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/ProductVendor.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/PurchaseOrderDetail.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/PurchaseOrderHeader.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/SalesOrderDetail.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/SalesOrderHeader.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/SalesOrderHeaderSalesReason.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/SalesPerson.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/SalesPersonQuotaHistory.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/SalesReason.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/SalesTaxRate.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/SalesTerritory.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/SalesTerritoryHistory.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/ScrapReason.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/Shift.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/ShipMethod.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/ShoppingCartItem.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/SpecialOffer.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/SpecialOfferProduct.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/StateProvince.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/Store.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/TransactionHistory.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/TransactionHistoryArchive.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/UnitMeasure.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/Vendor.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/WorkOrder.csv
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/adventureworks/data/WorkOrderRouting.csv
popd
